name: simple_calculator
description: Just a simple calculator. Nothing more.
publish_to: 'none'
version: 1.0.0+10

environment:
  sdk: ^3.12.2

dependencies:
  decimal: ^3.2.4
  flutter:
    sdk: flutter
  flutter_slidable: ^4.0.3
  function_tree: ^0.9.1
  provider: ^6.1.5+1
  rational: ^2.2.3
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_assets_generator:
  output_dir: services
  class_name: AssetsService
  output_filename: assets_service
  path_ignore: [ "assets" ]

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
          weight: 500
        - asset: assets/fonts/JetBrainsMono-Medium.ttf
          weight: 600
        - asset: assets/fonts/JetBrainsMono-Bold.ttf
          weight: 800
